### PR TITLE
added submodule, removed existing files

### PR DESCRIPTION
**Pull request by adkinsjd**
Everyone please make sure this works before we merge. I am also unsure why this isn't auto-merging, I'll look into that.

### CODE REVIEW

**Comment by adkinsjd** [comment]
I don't think it likes merging software deletions? Anyways I'll merge manually after everyone makes sure this works.

**Comment by ppannuto** [comment]
Those conflicts are because they are conflicts. Your PR is a few commits behind master, critically behind the bump to tock master commit:

```
[-bash] Tue 30 May 11:27 [[master] /Volumes/code/lab11/signpost]
$ git log master...origin/software-submodule
commit e9e8a6e0264de8784a935d6b3743eb632cdc6f2a (origin/software-submodule)
Author: Joshua Adkuins <adkins@berkeley.edu>
Date:   Mon May 29 18:53:32 2017 -0700

    added submodule, removed existing files

commit 55b73cdb8e69174db781e88887405cc8037017c5 (HEAD -> master, origin/master, origin/HEAD)
Author: Joshua Adkuins <adkins@berkeley.edu>
Date:   Mon May 29 14:41:36 2017 -0700

    moved travis files to software for the impending split

commit 5f1fd73293474ecff81bf0b482ea6a91c1f47fda
Author: Pat Pannuto <pat.pannuto@gmail.com>
Date:   Mon May 29 17:27:32 2017 -0400

    use vpath for app subdirectories

    @brghena I think this should address your issue from 9a35bbd

commit 0e94087d392443eb137b11228e824a2197d9224a
Merge: b182df2 ab77c88
Author: Pat Pannuto <pat.pannuto@gmail.com>
Date:   Mon May 29 17:05:45 2017 -0400

    Merge pull request #61 from lab11/bump_tock_master

    Bump tock to latest master

commit ab77c88c0c49ef4c5f700e061430c851f7a5d67d (origin/bump_tock_master)
Author: Pat Pannuto <pat.pannuto@gmail.com>
Date:   Mon May 29 16:23:21 2017 -0400

    Bump tock to latest master

      - Update apps for merged ltd294x driver
      - Update boards for new build system

    Everything compile-tested.
    Print energy app verified on controller/debug_backplane
```

**Comment by adkinsjd** [comment]
Thank makes more sense. Luckily sigmpost-software is not behind. I'll fix
after take off

**Comment by adkinsjd** [comment]
Okay it's easiest to delete this one and try again

**Pull request closed without merging**
